apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "astronomy.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.client.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.client.name }}
