apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "astronomy.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.client.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.name }}
        {{- include "astronomy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: client
          image: {{ include "astronomy.clientImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.client.port }}
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "astronomy.fullname" . }}-config
                  key: NEXT_PUBLIC_API_URL
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
